biaslab/biaslab-hugo

content/post/approach.md, content/post/mission.md, content/publication/the_graphical_brain.md
I added my paper w Friston. For some reason, when I do a `make website-preview` I see the change on the main screen but teh `details` button doesnt work. Perhaps you can correct this and let me know what I did wrong (for the future). thanks!
=> added Bert paper and minor edits

content/publication/A-factor-graph-description-of-active-inference.md
I added a publication. If it compiles, please merge.
=> add pub BdV and KF

config.toml, layouts/partials/slogan.html, static/css/biaslab.css
This PR updates the BIASlab website with mission statement in the header.
=> New landing

config.toml, content/vacancy/phd-bayesian-ml-for-dsp.md, layouts/partials/slogan.html, static/css/biaslab.css
This PR adds new PhD position in the group and adds an indication banner at the top of the page.
=> Open positions indication + PhD position

content/member/eric.md
@bertdv Please check the "Former members" section on our website and see if that matches your preferences.
=> Moved Eric's profile to "Former members" section

content/member/bert.md
=> updated link to bert CV

content/teaching/aip-5ssb0.md
Made some updates to the 5SSB0 homepage. please merge.
=> updated 5SSB0 homepage

content/teaching/aip-5ssb0.md
link update at 5SSB0 homepage. please merge
=> updated link to 5ssb0 pdf bundle

content/teaching/bmlip.md
=> Update BMLIP course website

content/teaching/bmlip.md
Adds subtitle property to bmlip.md
=> Teaching update

content/publication/worked-example-fokker.md
Let's hope I haven't reverted a bunch of stuff
=> Add IWAI publication

content/teaching/bmlip.md
- Added links to PP lecture notes in course material table.
- Added instructions on testing Julia and Jupyter installations using `Probabilistic-Programming-0.ipynb`.
- Added instructions on downloading source material from github.
=> Added links to PP lecture notes. 

content/project/simulating-football-players-decision-making-process.md
Nice work on the post @albertpod and @ThijnHermsen, I was reading it yesterday and just noticed this tiny spelling error. Wouldn't touch the rest, but this one jumped out :)
=> Fix minor spelling error in 'Simulated Soccer' project

content/publication/application-free-energy-principle.md, content/publication/chance-constrained-active-inference.md
This PR updates the published links for the CC and LQG papers.
=> Update links for cc and lqg papers

content/project/bayesian-pure-tone-audiometry.md, content/publication/bayesian-pure-tone-audiometry-through-active-learning-under-informed-priors.md
Add the [BPTA Through Active Learning Under Informed Priors](https://www.frontiersin.org/articles/10.3389/fdgth.2021.723348/full) paper to publications and update the corresponding project page.
=> Add Frontiers in Digital Health publication

content/publication/efe-lgds.md
This PR adds my entropy paper on epistemics in LGDS agents using EFE
=> add Epistemics in LGDS paper

content/publication/gaussian-process-based-amorization-of-vmp-ur.md, content/publication/hybrid-inference-INN.md, content/publication/mp-based-inference-in-swar.md
@albertpod @HoangMHNguyen Our EUSIPCO papers have been added to IEEE. I added these urls to the website, please check.
=> Update eusipco urls to IEEE

content/publication/mp-algos-dynamical-systems.md
=> Add Ismail thesis

content/publication/toward-design-of-synthetic-aif-agents-by-mere-mortals.md
Bert's IWAI 2023 paper should appear with this branch
=> 📜: update IWAI 2023 paper by Bert

content/publication/principled_pruning_BNN.md
Updated the BNN pruning paper after being published in IEEE OJSP.
=> Update BNN pruning paper

content/member/thijs.md, content/open-projects/msc-system-diagnostics.md, layouts/section/open-projects.html
This PR 1) fixes the github link on Thijs' profile page, and 2) updates the MSc project page with an additional project in the system diagnostics category.
=> Update GH link and MSc project page

content/publication/A-factor-graph-approach-to-variational-sparse-gaussian-processes.md
Add paper "A Factor Graph Approach to Variational Sparse Gaussian Processes"
=> add paper A Factor Graph Approach to Variational Sparse Gaussian Processes
